src/objects/Account/fields/Customer_classification__c.field-meta.xml
<CustomField>
    <fullName>Customer_classification__c</fullName>
    <description>Used to display the customer classification. Value decided from - Total_Customer_Spend__c field.</description>
    <formula>IF(Total_Customer_Spend__c &gt;= 50000, &quot;GOLD&quot;,
IF(Total_Customer_Spend__c &gt;= 25000, &quot;SILVER&quot;,
IF(Total_Customer_Spend__c &gt;= 10000, &quot;BRONZE&quot;, &quot;&quot;) ) )</formula>
    <label>Customer classification</label>
    <type>Text</type>
</CustomField>

src/objects/CEO_info__c/CEO_info__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CEO_info</label>
</CustomObject>

src/classes/AccountTriggerClass.cls
/***************************************************************
 * Class: AccountTriggerClass
 * Description: Code for Account trigger class
 * Created on - 14.August.2022
 * Author-Bhuvaneshwari R
 * ***********************************************************/

public class AccountTriggerClass {
    
    // function to make the call from trigger to twilio api based on criteria check.
    public static void callTwilioAPI(Map<Id,SObject> newItems, Map<Id,SObject> oldItems){
        List<Account> newAccountList = newItems.values();
        //fecthing values of CEO from custom settings
        list<CEO_info__c> ceoUser = CEO_info__c.getall().values();
        for(Account newAcc: newAccountList){
            Account oldAcc = (Account)oldItems.get(newAcc.Id);
            //check for first time GOLD customer and send sms to ceo
            if(newAcc.Customer_classification__c=='GOLD' && oldAcc.Customer_classification__c!='GOLD'){
                //call api with sms body mentioned
                String smsBody = 'Great News! A Customer has hit Gold.'+newAcc.Name+' will get VIP treatment';
                TwilioAPIApex.TwilioAPICallout(smsBody,ceoUser[0].PhoneNumber__c);
            }
        }
    }

}